<?php
//src/BG/BlogBundle/Entity/BilletRepository.php

namespace BG\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
    {
        return $this
            ->createQueryBuilder('b')
            ->getQuery()
            ->getResult()
        ;
    }

    public function myFind($id)
    {
        $qb=$this->createQueryBuilder('b');

        $qb
            ->where('b.id=:id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }


}
